# Generated by Django 3.0.8 on 2020-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200819_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='pic_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile_pic',
            old_name='user',
            new_name='pic_by',
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
