# Generated by Django 3.0.8 on 2020-08-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200819_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_pic',
            name='pic_by',
        ),
        migrations.AddField(
            model_name='profile_pic',
            name='photo_of',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='my_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
