# Generated by Django 3.0.8 on 2020-08-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200819_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_pic',
            new_name='Profile',
        ),
    ]
